{{- if .Values.cdcBridge.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "maestro.fullname" . }}-cdc-bridge
  labels:
    {{- include "maestro.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: cdc-bridge
spec:
  type: ClusterIP
  ports:
    - port: 8091
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "maestro.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: cdc-bridge
{{- end }}
