spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:postgresql://postgres:5432/hapi_fhir
    username: maestro
    password: maestro_local_pg_pass
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgres94Dialect
        format_sql: false

hapi:
  fhir:
    fhir_version: R4
    server_address: https://fhir.austahospital.com.br/fhir
