global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: "cib7-workers"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "worker-billing:8000"
          - "worker-auth:8000"
          - "worker-coding:8000"
          - "worker-denials:8000"
          - "worker-analytics:8000"
    relabel_configs:
      - source_labels: [__address__]
        regex: "(.*):.*"
        target_label: instance

  - job_name: "cib7-engine"
    metrics_path: "/engine-rest/metrics"
    static_configs:
      - targets:
          - "cib7-engine:8080"
